<?php

/**
 * @file
 * User interface for the OpenSearch feed module.
 */

/**
 * Implements hook_menu().
 */
function opensearch_ui_menu() {
  $items = array();

  $items['admin/config/opensearch/settings'] = array(
    'title' => 'OpenSearch settings',
    'description' => 'Allows search results to be returned as OpenSearch RSS.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('opensearch_ui_admin_settings'),
    'access arguments' => array('administer search'),
    'weight' => -11,
    'file' => 'opensearch_ui.admin.inc',
  );
  $items['admin/config/opensearch/settings/%opensearch_type'] = array(
    'title' => 'OpenSearch settings',
    'description' => 'These are the settings for the OpenSearch feed.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('opensearch_ui_admin_type_settings', 4),
    'access arguments' => array('administer search'),
    'type' => MENU_CALLBACK,
    'file' => 'opensearch_ui.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function opensearch_ui_theme() {
  return array(
    'opensearch_ui_description_files' => array(
      'render element' => 'form',
      'file' => 'opensearch_ui.admin.inc',
    ),
  );
}
